package com.microsoft.hsf302_project.enums;

public enum NotificationType {
    FRIEND_REQUEST, FRIEND_ACCEPT, FRIEND_REJECT, ALBUM_ACCESS_REQUEST, POST_LIKE,POST_DISLIKE, POST_COMMENT,APPROVE_REQUEST_ACCESS,REJECT_REQUEST_ACCESS
    , ACCOUNT_LOCKED, ACCOUNT_UNLOCKED
}
